library(bayesLife)
source('test_functions.R')
#test.estimate.mcmc.with.same.z()
test.estimate.mcmc.with.suppl.data()
test.get.wpp.data()
test.estimate.mcmc()
#test.estimate.mcmc.with.same.z()
test.existing.simulation()
test.DLcurve()
test.e0trajectories()
test.plot.density()
test.get.parameter.traces()
test.plot.map()

test.run.mcmc.simulation.auto()
