library(bayesLife)
source('test_functions.R')
test.get.wpp.data()
test.estimate.mcmc()
test.existing.simulation()
test.DLcurve()
test.e0trajectories()
test.plot.density()
test.get.parameter.traces()
test.plot.map()

#test.run.mcmc.simulation.auto()
